### ISSUE TITLE
v1.11 npm package broken?

### ISSUE THREAD

**Issue by chriskiefer** [vaheqelyan/svelte-grid#37] opened 2020-07-30 13:32 UTC
Hi,  the latest version of the npm package won't build for some reason - although it works fine using the version from this repo.

**Comment by frantic0** [comment] 2020-07-30 13:43
It was lacking a rollup-plugin-svelte

```
svelte-grid $ npm run build

> svelte-grid@1.11.0 build /Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte-grid
> rollup -c

[!] Error: Cannot find module 'rollup-plugin-svelte'
Require stack:
- /Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte-grid/rollup.config.js
- /Users/francisco/Documents/dev/MIMIC/sema/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'rollup-plugin-svelte'
Require stack:
- /Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte-grid/rollup.config.js
- /Users/francisco/Documents/dev/MIMIC/sema/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte-grid/rollup.config.js:7:30)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.require.extensions.<computed> [as .js] (/Users/francisco/Documents/dev/MIMIC/sema/node_modules/rollup/dist/bin/rollup:824:24)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-grid@1.11.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-grid@1.11.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/francisco/.npm/_logs/2020-07-30T13_39_17_936Z-debug.log
```

**Comment by vaheqelyan** [comment] 2020-08-01 16:04
Forgive me, I'll take a quick look

**Comment by vaheqelyan** [comment] 2020-08-01 16:29
ok, seems to be fixed. install version v1.11.1. feel free to reopen

**Comment by smilo7** [comment] 2020-08-05 14:15
Hi I am getting a similar error. Despite using the solution above it still fails to build, even with the latest version. 
`svelte-grid]$ npm run build

> svelte-grid@1.11.0 build /home/mi/Documents/newSemaTest/bug/sema/node_modules/svelte-grid
> rollup -c

Error: ENOENT: no such file or directory, lstat '/home/mi/Documents/newSemaTest/bug/sema/node_modules/svelte-grid/rollup.config.js'
    at Object.realpathSync (fs.js:1680:7)
    at runRollup (/home/mi/Documents/newSemaTest/bug/sema/node_modules/svelte-grid/node_modules/rollup/dist/bin/rollup:1327:29)
    at Object.<anonymous> (/home/mi/Documents/newSemaTest/bug/sema/node_modules/svelte-grid/node_modules/rollup/dist/bin/rollup:1455:5)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-grid@1.11.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svelte-grid@1.11.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mi/.npm/_logs/2020-08-05T14_14_35_308Z-debug.log
`

**Comment by vaheqelyan** [comment] 2020-08-17 10:01
@smilo7 can you create a github repo that reproduces your issue.

**Comment by vaheqelyan** [comment] 2020-08-20 08:23
closing the issue

**Closed by vaheqelyan** 2020-08-20 08:23 UTC
